### ISSUE TITLE
how to simlate stall ?

### ISSUE THREAD

**Issue by EpicSpaces** [gasgiant/Aircraft-Physics#1]
I wanted to simulate stall like DCS, or Lock on FC, in the F15 , Su 27 , there is always that pitch locked at high aoa(angle of attack), so how one can reproduce this https://imgur.com/a/BT6J9Yc the aoa remains high until the pilot do some manoeuver(moving the stick forward) to recover ? (because here it falls back to the velocity vector whatever I do). is there a trick that DCS or Lock on series does ?

**Comment by gasgiant** [comment]
Hi! I'm not sure I correctly understood the question. I think, whether a plane recovers from the stall by itself or not highly depends on its characteristics. When playing with this system I've even experieced unrecoverable spins. However I should note that this model is not a great choice to realistically model fighter jets. It doesn't handle supersonic aerodynamics in any way. Also I suspect that in case of fighter jets interactions between surfaces are too important to ignore.

**Comment by EpicSpaces** [comment]
Yes, I finally get it, because games use Flaps. Okay anyway forget about it, Can you give an intuition about how did calculated the coefficients, the math behind looks complicated, I even plotted for different aoa.

**Comment by gasgiant** [comment]
I used the article  W. Khan and M. Nahon, "Real-time modeling of agile fixed-wing UAV aerodynamics," 2015 International Conference on Unmanned Aircraft Systems (ICUAS), Denver, CO, 2015, pp. 1188-1195, doi: 10.1109/ICUAS.2015.7152411. 

I'm not a specialist but in general it works as follows. In low AoA range it uses something like thin airfoil theory. At high angles of attack it treats the surface as a plate, that's possibly curved due to the control surface. In between of these two modes I interpolate between border values of them, though the paper is not clear on this process. For more detailed look you should check the article and possibly references inside it.
